global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
- job_name: %job_name%
  scrape_interval: %scrape_interval%
  dns_sd_configs:
  - names:
%dns_sd_names%
  relabel_configs:
    - source_labels: [%relabel_source_labels%]
      regex: %relabel_regex%
      replacement: %relabel_replacement%
      modulus: %relabel_modulus%
      target_label: %relabel_target_label%
      action: %relabel_action%
  basic_auth:
    username: %auth_user%
    password: %auth_pass%
